# Bearded Theme: Arc Blueberry
# Ported from: https://github.com/BeardedBear/bearded-theme

[colors.primary]
background = '#111422'
foreground = '#bcc1dc'

[colors.cursor]
text   = '#111422'
cursor = '#8eb0e6'

[colors.selection]
text       = 'CellForeground'
background = '#222944'

[colors.normal]
black   = '#111422'
red     = '#e35535'
green   = '#3cec85'
yellow  = '#eacd61'
blue    = '#8eb0e6'
magenta = '#f38cec'
cyan    = '#2aa198'
white   = '#bcc1dc'

[colors.bright]
black   = '#434d7d'
red     = '#e35535'
green   = '#3cec85'
yellow  = '#eacd61'
blue    = '#8eb0e6'
magenta = '#f38cec'
cyan    = '#2aa198'
white   = '#ffffff'
